name: CI-CD
on:
  push: { branches: [ "main" ] }
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: pytest -q
  build_and_push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract short sha
        id: meta
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ secrets.IMAGE_NAME }}:latest
            ${{ secrets.IMAGE_NAME }}:${{ steps.meta.outputs.SHORT_SHA }}
      - name: Call deploy webhook
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          curl -X POST "$WEBHOOK_URL" \
            -H "Content-Type: application/json" \
            -d "{\"image\":\"${{ secrets.IMAGE_NAME }}:${{ steps.meta.outputs.SHORT_SHA }}\"}"
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
